### ISSUE TITLE
form在子窗口中打开摄像头，第一次打开可以，第二次打开就显示connecting....

### ISSUE THREAD

**Issue by yushiweiwie** [liemei/baiduAIFaceIdentify#2]
private void FaceSearch_Load(object sender, EventArgs e) {

			videoSourcePlayer2.SignalToStop();
			videoSourcePlayer2.WaitForStop();
			//videoDevices = new FilterInfoCollection(FilterCategory.VideoInputDevice);
			VideoCaptureDevice videoSource = new VideoCaptureDevice(videoDevices[0].MonikerString);
			videoSource.DesiredFrameSize = new System.Drawing.Size(320, 240);
			videoSource.DesiredFrameRate = 1;
			videoSourcePlayer2.VideoSource = videoSource;
			videoSource.Start();
			videoSourcePlayer2.Start();
			videoSourcePlayer2.NewFrame += videoSourcePlayer2_NewFrame;

			// 开发者在百度AI平台人脸识别接口只能1秒中调用2次，所以需要做 定时开始检测，每个一秒检测2次
			ThreadPool.QueueUserWorkItem(new WaitCallback(p => {

				while ( this.Visible ) {
					IsStart = true;
					Thread.Sleep(500);
				}
			}));

		}
在子窗口的代码如下，
第一次打开子窗口的时候，是能看到摄像头并且能进行人脸检测的。但是关闭form之后，再次打开，就不可以，一直显示connecting ...
楼主若看到，还请帮忙指导一下。不胜感激。

**Comment by liemei** [comment]
你关闭form的时候没有关闭摄像头吧

**Comment by yushiweiwie** [comment]
是的 ，是没有关闭掉摄像头的缘故 
在窗体关闭的时候  加上这句就好了
videoSourcePlayer1.Stop();
